sudo: required
dist: trusty

language: java
jdk:
- openjdk8
- oraclejdk8

before_script:
  - bash ./setversion.sh

env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: ./gradlew setupCIWorkspace
script: ./gradlew build

notifications:
  email: false

before_deploy:
  - for f in "./build/libs/FoxCore*SNAPSHOT.jar"; do mv ${f} "./build/libs/FoxCore-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-SNAPSHOT.jar"; done
  - for f in "./build/libs/FoxCore*SNAPSHOT-all.jar"; do mv ${f} "./build/libs/FoxCore-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-SNAPSHOT-all.jar"; done
  - for f in "./build/libs/FoxCore*SNAPSHOT-sources.jar"; do mv ${f} "./build/libs/FoxCore-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-SNAPSHOT-sources.jar"; done

deploy:
  file_glob: true
  provider: releases
  api-key: ${KEY}
  file: "./build/libs/FoxCore*.jar"
  skip_cleanup: true
  on:
    tags: true